#ifndef SNFD_CONFIG_H
#define SNFD_CONFIG_H

#ifndef SNFD_EXCHANGE_BUFFER_SIZE
#define SNFD_EXCHANGE_BUFFER_SIZE 128
#endif

#ifndef SNFD_MAGIC_NUMBER_SIZE
#define SNFD_MAGIC_NUMBER_SIZE 15
#endif


#ifndef SNFD_BLOCKS_COUNT
#define SNFD_BLOCKS_COUNT 256
#endif

#ifndef SNFD_BLOCK_SIZE
#define SNFD_BLOCK_SIZE 4096
#endif

#ifndef SNFD_MAGIC_NUMBER
#define SNFD_MAGIC_NUMBER "SNFD1234567SNFD"
#endif


#endif /* end of include guard: SNFD_CONFIG_H */
